### PR TITLE
To find the length of the last word of the string

### PR DESCRIPTION
**Pull request by ankiiisharma**
Given a string s consisting of words and spaces, return the length of the last word in the string. @MridulTi

### CODE REVIEW

**Review by MridulTi — CHANGES_REQUESTED** [review]
can you remove the .exe file

**Comment by ankiiisharma** [comment]
@MridulTi Done

**Comment by MridulTi** [comment]
> @MridulTi Done
You have delete the cpp file bymistakenly and not the .exe file

**Comment by ankiiisharma** [comment]
@MridulTi I'm not able to delete this file. Can you please delete this from your side?

**Comment by MridulTi** [comment]
> @MridulTi I'm not able to delete this file. Can you please delete this from your side?

do one this I am delete this PR now make a new branch and there delete .exe file and them add , commit and push and create another PR

**Comment by ankiiisharma** [comment]
@MridulTi sure,

**Pull request closed without merging**
